In [55]:
import numpy as np
import math as mt

class sudoku:
    def __init__(self, grid):
        self.grid = grid #9x9 matrix, initial version of the sudoku that is to be solved. Empty spaces are 0.
        self.ghost = {i:list(range(1,10)) for i in range(81)} #by_horizontal_index
        self.__g__() #run ghosts at initialization
        
    def __get_box_indexes__(self, position):
        row_int = (position[0])//3
        col_int = (position[1])//3
        positions = [(row+row_int*3,col+col_int*3) for row in range(3) for col in range(3)]
        indexes = [a*9+b for a,b in positions]
        return indexes
    
    def grid(self):
        print(self.grid)
        
    def __g__(self): #pencil marker
        for i in range(9):
            for j in range(9):
                if self.grid[i,j] == 0:
                    continue

                self.ghost[i*9+j] = []

                column_i = [an for an in range(j,81,9)]
                row_i = [an+i*9 for an in range(9)]
                box_i = self.__get_box_indexes__([i,j])

                for k in column_i:
                    if self.grid[i,j] in self.ghost[k]:
                        self.ghost[k].remove(self.grid[i,j])
                for k in row_i:
                    if self.grid[i,j] in self.ghost[k]:
                        self.ghost[k].remove(self.grid[i,j])
                for k in box_i:
                    if self.grid[i,j] in self.ghost[k]:
                        self.ghost[k].remove(self.grid[i,j])
    
    def solve_easy(self): #Sudokus that can be solved with naked singles only.
        flag = 0
        while flag == 0:
            for index, l in list(self.ghost.items()):
                if len(l) == 1:
                    self.grid[index//9, index%9] = l[0]
                    self.ghost = {i:list(range(1,10)) for i in range(81)}
                    self.__g__()
                    break
                if index == len(list(self.ghost.items()))-1:
                    flag = 1
        print(self.grid)
    
    def pencil_marks(self):
        for i in range(81):
            print(self.ghost[i])

In [56]:
k = np.array([[ 0, 0, 4, 0, 0, 0, 0, 6, 7 ],
              [ 3, 0, 0, 4, 7, 0, 0, 0, 5 ],
              [ 1, 5, 0, 8, 2, 0, 0, 0, 3 ],
              [ 0, 0, 6, 0, 0, 0, 0, 3, 1 ],
              [ 8, 0, 2, 1, 0, 5, 6, 0, 4 ],
              [ 4, 1, 0, 0, 0, 0, 9, 0, 0 ],
              [ 7, 0, 0, 0, 8, 0, 0, 4, 6 ],
              [ 6, 0, 0, 0, 1, 2, 0, 0, 0 ],
              [ 9, 3, 0, 0, 0, 0, 7, 1, 0 ]])
l = sudoku(k)
l.solve_easy()

[[2 8 4 5 9 3 1 6 7]
 [3 6 9 4 7 1 8 2 5]
 [1 5 7 8 2 6 4 9 3]
 [5 7 6 9 4 8 2 3 1]
 [8 9 2 1 3 5 6 7 4]
 [4 1 3 2 6 7 9 5 8]
 [7 2 1 3 8 9 5 4 6]
 [6 4 5 7 1 2 3 8 9]
 [9 3 8 6 5 4 7 1 2]]
